added retry on non zero codes

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -50,10 +50,22 @@ stages:
         scriptType: bash
         scriptLocation: inlineScript
         inlineScript: |
-          docker images
-          defender scan image $(containerRegistry)/$(backendRepository):$(tag) \
-            --defender-output $(Build.ArtifactStagingDirectory)/$(backendRepository).sarif \
-            --defender-break
+          for i in 1 2 3; do
+            defender scan image $(containerRegistry)/$(backendRepository):$(tag) \
+              --defender-output $(Build.ArtifactStagingDirectory)/$(backendRepository).sarif \
+              --defender-break
+            rc=$?
+            if [ $rc -eq 0 ]; then
+              break
+            fi
+            if [ $rc -ne 0 ] && [ $i -lt 3 ]; then
+              echo "Scan failed with exit code $rc, retrying..."
+              sleep 10
+            else
+              echo "Scan failed with exit code $rc"
+              exit $rc
+            fi
+          done
       env:
         DEFENDER_TENANT_ID: $(DEFENDER_TENANT_ID)
         DEFENDER_CLIENT_ID: $(DEFENDER_CLIENT_ID)
@@ -81,11 +93,22 @@ stages:
           docker tag ghcr.io/indicate-eu/benchmarking-data-exchange-server:latest $(containerRegistry)/$(frontendRepository):$(tag)
           docker tag ghcr.io/indicate-eu/benchmarking-data-exchange-server:latest $(containerRegistry)/$(frontendRepository):latest
 
-          docker images
-          defender scan image $(containerRegistry)/$(frontendRepository):$(tag) \
-                    --defender-output $(Build.ArtifactStagingDirectory)/$(frontendRepository).sarif \
-                    --defender-break
-
+          for i in 1 2 3; do
+            defender scan image $(containerRegistry)/$(frontendRepository):$(tag) \
+              --defender-output $(Build.ArtifactStagingDirectory)/$(frontendRepository).sarif \
+              --defender-break
+            rc=$?
+            if [ $rc -eq 0 ]; then
+              break
+            fi
+            if [ $rc -ne 0 ] && [ $i -lt 3 ]; then
+              echo "Scan failed with exit code $rc, retrying..."
+              sleep 10
+            else
+              echo "Scan failed with exit code $rc"
+              exit $rc
+            fi
+          done
 
           docker push $(containerRegistry)/$(frontendRepository):$(tag)
           docker push $(containerRegistry)/$(frontendRepository):latest
